rainforest/config/routes.rb
Rainforest::Application.routes.draw do
  root :to => "products#index"
  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :products do
    resources :reviews, :except => [:index]
  end

end

rainforest/app/models/product.rb
class Product < ActiveRecord::Base
	validates :description, :name, :url, :presence => true
	validates :price_in_cents, :numericality => {:only_integer => true}
	has_many :reviews
	has_many :users, :through => :reviews

	#validates :url, presence: true

	#validates_presence_of :name, :description, :url

	def formatted_price
        price_in_dollars = price_in_cents.to_f / 100
        sprintf("$%.2f", price_in_dollars)
    end
end

rainforest/app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
end

rainforest/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :reviews
	has_many :products, :through => :reviews
	validates_presence_of :name
end

rainforest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

helper_method :current_user

	def ensure_logged_in
		unless current_user
			flash[:alert] = "Please log in"
			redirect_to new_session_path
		end
	end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


end

rainforest/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :ensure_logged_in, :only => [:show]
  #only ensure logged in for show.

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents, :url)
  end
end

rainforest/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_product
  #so that there's always a product loaded
  before_filter :ensure_logged_in, :only => [:show, :create, :show, :update, :destroy]
  #only ensure logged in for the methods in the hash.

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user_id = current_user.id

    # Check out this article on [.build](http://stackoverflow.com/questions/783584/ruby-on-rails-how-do-i-use-the-active-record-build-method-in-a-belongs-to-rel)
    # You could use a longer alternate syntax if it makes more sense to you
    #
    # @review = Review.new(
    #   :comment    => params[:review][:comment],
    #   :product_id => @product.id,
    #   :user_id    => current_user.id
    # )

    if @review.save
      redirect_to products_path, notice: 'Review created successfully'
    else
      render :action => :show
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

rainforest/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged out!"
  end
end

rainforest/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to products_url, :notice => "Signed up!"
  	else
  		render "new"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

rainforest/app/helpers/application_helper.rb
module ApplicationHelper
end

rainforest/app/helpers/products_helper.rb
module ProductsHelper
end

rainforest/app/helpers/reviews_helper.rb
module ReviewsHelper
end

rainforest/app/helpers/sessions_helper.rb
module SessionsHelper
end

rainforest/app/helpers/users_helper.rb
module UsersHelper
end

rainforest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="fixed">
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Rainforest", root_url %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->

    <ul class="right">
      <li class="active"><%= link_to "New product", new_product_path %></li>
      <% if current_user %>
        <li class="active"> <font color = white>Signed in as <%= current_user.name %></font>
        <li class="active"><%= link_to "Log out", session_path(current_user), :method => :delete %></li>
      <% else %>
        <li class="active"><%= link_to "Sign up", new_user_path %></li>
        <li class="active"><%= link_to "Log in", new_session_path %></li>
      <% end %>

<!--       <li class="has-dropdown">
        <a href="#">Right Button with Dropdown</a>
        <ul class="dropdown">
          <li><a href="#">First link in dropdown</a></li>
        </ul>
      </li> -->
    </ul>

    <!-- Left Nav Section -->

  </section>
</nav>
  </div>

   <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>
    <body>
     <%= javascript_include_tag "application", "data-turbolinks-track" => true %>



      <%= yield %>
      <%= params %>
  </body>
</html>

rainforest/app/views/products/_form.html.erb
<%= form_for @product do |f| %>
<% if @product.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product: from being saved:</h2>


	<ul>
		<% @product.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="small-6 large-8 columns">
<div class="field">
	<%= f.label "name" %><br>
	<%= f.text_field "name" %>
</div>
<div class="field">
	<%= f.label "description" %><br>
	<%= f.text_area "description" %>
</div>
<div class="field">
	<%= f.label "price in cents" %><br>
	<%= f.number_field "price_in_cents" %>
</div>

<div class="field">
	<%= f.label "url" %><br>
	<%= f.text_field "url" %>
</div>
<div class="actions">

	<%= f.submit "Save" %>
</div>

<% end %>
</div>

rainforest/app/views/products/edit.html.erb
<h1>Edit a product</h1>
<%= render 'form' %>
<%= link_to 'Back', products_path %>

rainforest/app/views/products/index.html.erb
<h1> Products (<%= @products.length %>)</h1>
<%= link_to "New Product", "/products/new" %>

<% @products.each do |product| %>
<p><%= product.name %>, <%= product.description %>, <%= product.formatted_price %></p>
<%= link_to (image_tag product.url, width: '200'), product %>
<% end %>

<!--@product[:name] and @product[:description] is the same as @product.name and @product.description-->

rainforest/app/views/products/new.html.erb
<%= link_to 'Back', products_path %>

<h1>Add a product</h1>

<%= render 'form' %>

rainforest/app/views/products/show.html.erb
<br />
<%= link_to "Back to Products", products_url %> | <%= link_to "Edit", edit_product_path(@product) %> | <%= link_to "Delete", @product, :confirm => "Are you sure you want to delete this product?", :method => :delete %>

<p><%= @product.name %>, <%= @product.description %>, <%= @product.formatted_price %></p>
<%= image_tag @product.url %>

<!--@product[:name] and @product[:description] is the same as @product.name and @product.description-->

<% if current_user %>

  <h3>Reviews</h3>

  <p>Reviews for <%= @product.name %></p>

  <% @product.reviews.each do |review| %>
    <p>
      <%= review.comment %>
      <br>
      <% if review.user != nil %>
        <em> by <%= review.user.name %></em>
        Added on: <%= review.created_at %>
      <% end %>
    </p>
  <% end %>

  <h4>New Review</h4>

  <%= form_for([@product, @review]) do |f| %>

    <% if @review.errors.any? %>
      <div id="error_explanation">
      	<h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      	<ul>
      		<% @review.errors.full_messages.each do |msg| %>
        		<li><%= msg %></li>
      		<% end %>
      	</ul>
      </div>
    <% end %>

    <div class="field">
    	<%= f.label :comment %><br />
    	<%= f.text_area :comment %>
    </div>
    <div class="actions">
    	<%= f.submit %>
    </div>

  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
<% end %>

rainforest/app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

rainforest/app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

rainforest/app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

rainforest/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="small-6 large-8 columns">

  <div class = "field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions"><%= f.submit %>
  </div>
<% end %>

</div>